export type Country = {
  name: string;
  code: string;
  text?: string;
};

export const COUNTRIES: Record<string, Country> = {
  Q16: { name: "Canada", code: "CA", text: "Citizen of Canada (Wikidata)" },
  Q17: { name: "Japan", code: "JP", text: "Citizen of Japan (Wikidata)" },
  Q20: { name: "Norway", code: "NO", text: "Citizen of Norway (Wikidata)" },
  Q27: { name: "Ireland", code: "IE", text: "Citizen of Ireland (Wikidata)" },
  Q28: { name: "Hungary", code: "HU", text: "Citizen of Hungary (Wikidata)" },
  Q30: {
    name: "United States of America",
    code: "US",
    text: "Citizen of United States of America (Wikidata)",
  },
  Q33: { name: "Finland", code: "FI", text: "Citizen of Finland (Wikidata)" },
  Q34: { name: "Sweden", code: "SE", text: "Citizen of Sweden (Wikidata)" },
  Q35: { name: "Denmark", code: "DK", text: "Citizen of Denmark (Wikidata)" },
  Q36: { name: "Poland", code: "PL", text: "Citizen of Poland (Wikidata)" },
  Q38: { name: "Italy", code: "IT", text: "Citizen of Italy (Wikidata)" },
  Q39: {
    name: "Switzerland",
    code: "CH",
    text: "Citizen of Switzerland (Wikidata)",
  },
  Q40: { name: "Austria", code: "AT", text: "Citizen of Austria (Wikidata)" },
  Q41: { name: "Greece", code: "GR", text: "Citizen of Greece (Wikidata)" },
  Q43: { name: "Turkey", code: "TR", text: "Citizen of Turkey (Wikidata)" },
  Q45: { name: "Portugal", code: "PT", text: "Citizen of Portugal (Wikidata)" },
  Q55: {
    name: "Netherlands",
    code: "NL",
    text: "Citizen of Netherlands (Wikidata)",
  },
  Q77: { name: "Uruguay", code: "UY", text: "Citizen of Uruguay (Wikidata)" },
  Q79: { name: "Egypt", code: "EG", text: "Citizen of Egypt (Wikidata)" },
  Q96: { name: "Mexico", code: "MX", text: "Citizen of Mexico (Wikidata)" },
  Q114: { name: "Kenya", code: "KE", text: "Citizen of Kenya (Wikidata)" },
  Q115: {
    name: "Ethiopia",
    code: "ET",
    text: "Citizen of Ethiopia (Wikidata)",
  },
  Q117: { name: "Ghana", code: "GH", text: "Citizen of Ghana (Wikidata)" },
  Q142: { name: "France", code: "FR", text: "Citizen of France (Wikidata)" },
  Q145: {
    name: "United Kingdom",
    code: "GB",
    text: "Citizen of United Kingdom (Wikidata)",
  },
  Q148: {
    name: "People's Republic of China",
    code: "CN",
    text: "Citizen of People's Republic of China (Wikidata)",
  },
  Q155: { name: "Brazil", code: "BR", text: "Citizen of Brazil (Wikidata)" },
  Q183: { name: "Germany", code: "DE", text: "Citizen of Germany (Wikidata)" },
  Q184: { name: "Belarus", code: "BY", text: "Citizen of Belarus (Wikidata)" },
  Q211: { name: "Latvia", code: "LV", text: "Citizen of Latvia (Wikidata)" },
  Q213: {
    name: "Czech Republic",
    code: "CZ",
    text: "Citizen of Czech Republic (Wikidata)",
  },
  Q214: {
    name: "Slovakia",
    code: "SK",
    text: "Citizen of Slovakia (Wikidata)",
  },
  Q218: { name: "Romania", code: "RO", text: "Citizen of Romania (Wikidata)" },
  Q219: {
    name: "Bulgaria",
    code: "BG",
    text: "Citizen of Bulgaria (Wikidata)",
  },
  Q222: { name: "Albania", code: "AL", text: "Citizen of Albania (Wikidata)" },
  Q224: { name: "Croatia", code: "HR", text: "Citizen of Croatia (Wikidata)" },
  Q228: { name: "Andorra", code: "AD", text: "Citizen of Andorra (Wikidata)" },
  Q229: { name: "Cyprus", code: "CY", text: "Citizen of Cyprus (Wikidata)" },
  Q232: {
    name: "Kazakhstan",
    code: "KZ",
    text: "Citizen of Kazakhstan (Wikidata)",
  },
  Q233: { name: "Malta", code: "MT", text: "Citizen of Malta (Wikidata)" },
  Q236: {
    name: "Montenegro",
    code: "ME",
    text: "Citizen of Montenegro (Wikidata)",
  },
  Q241: { name: "Cuba", code: "CU", text: "Citizen of Cuba (Wikidata)" },
  Q244: {
    name: "Barbados",
    code: "BB",
    text: "Citizen of Barbados (Wikidata)",
  },
  Q252: {
    name: "Indonesia",
    code: "ID",
    text: "Citizen of Indonesia (Wikidata)",
  },
  Q258: {
    name: "South Africa",
    code: "ZA",
    text: "Citizen of South Africa (Wikidata)",
  },
  Q262: { name: "Algeria", code: "DZ", text: "Citizen of Algeria (Wikidata)" },
  Q265: {
    name: "Uzbekistan",
    code: "UZ",
    text: "Citizen of Uzbekistan (Wikidata)",
  },
  Q298: { name: "Chile", code: "CL", text: "Citizen of Chile (Wikidata)" },
  Q334: {
    name: "Singapore",
    code: "SG",
    text: "Citizen of Singapore (Wikidata)",
  },
  Q347: {
    name: "Liechtenstein",
    code: "LI",
    text: "Citizen of Liechtenstein (Wikidata)",
  },
  Q398: { name: "Bahrain", code: "BH", text: "Citizen of Bahrain (Wikidata)" },
  Q408: {
    name: "Australia",
    code: "AU",
    text: "Citizen of Australia (Wikidata)",
  },
  Q414: {
    name: "Argentina",
    code: "AR",
    text: "Citizen of Argentina (Wikidata)",
  },
  Q419: { name: "Peru", code: "PE", text: "Citizen of Peru (Wikidata)" },
  Q423: {
    name: "North Korea",
    code: "KP",
    text: "Citizen of North Korea (Wikidata)",
  },
  Q424: {
    name: "Cambodia",
    code: "KH",
    text: "Citizen of Cambodia (Wikidata)",
  },
  Q574: {
    name: "East Timor",
    code: "TL",
    text: "Citizen of East Timor (Wikidata)",
  },
  Q657: { name: "Chad", code: "TD", text: "Citizen of Chad (Wikidata)" },
  Q664: {
    name: "New Zealand",
    code: "NZ",
    text: "Citizen of New Zealand (Wikidata)",
  },
  Q668: { name: "India", code: "IN", text: "Citizen of India (Wikidata)" },
  Q672: { name: "Tuvalu", code: "TV", text: "Citizen of Tuvalu (Wikidata)" },
  Q683: { name: "Samoa", code: "WS", text: "Citizen of Samoa (Wikidata)" },
  Q685: {
    name: "Solomon Islands",
    code: "SB",
    text: "Citizen of Solomon Islands (Wikidata)",
  },
  Q686: { name: "Vanuatu", code: "VU", text: "Citizen of Vanuatu (Wikidata)" },
  Q691: {
    name: "Papua New Guinea",
    code: "PG",
    text: "Citizen of Papua New Guinea (Wikidata)",
  },
  Q695: { name: "Palau", code: "PW", text: "Citizen of Palau (Wikidata)" },
  Q697: { name: "Nauru", code: "NR", text: "Citizen of Nauru (Wikidata)" },
  Q702: {
    name: "Federated States of Micronesia",
    code: "FM",
    text: "Citizen of Federated States of Micronesia (Wikidata)",
  },
  Q709: {
    name: "Marshall Islands",
    code: "MH",
    text: "Citizen of Marshall Islands (Wikidata)",
  },
  Q710: {
    name: "Kiribati",
    code: "KI",
    text: "Citizen of Kiribati (Wikidata)",
  },
  Q711: {
    name: "Mongolia",
    code: "MN",
    text: "Citizen of Mongolia (Wikidata)",
  },
  Q712: { name: "Fiji", code: "FJ", text: "Citizen of Fiji (Wikidata)" },
  Q717: {
    name: "Venezuela",
    code: "VE",
    text: "Citizen of Venezuela (Wikidata)",
  },
  Q733: {
    name: "Paraguay",
    code: "PY",
    text: "Citizen of Paraguay (Wikidata)",
  },
  Q734: { name: "Guyana", code: "GY", text: "Citizen of Guyana (Wikidata)" },
  Q736: { name: "Ecuador", code: "EC", text: "Citizen of Ecuador (Wikidata)" },
  Q739: {
    name: "Colombia",
    code: "CO",
    text: "Citizen of Colombia (Wikidata)",
  },
  Q750: { name: "Bolivia", code: "BO", text: "Citizen of Bolivia (Wikidata)" },
  Q754: {
    name: "Trinidad and Tobago",
    code: "TT",
    text: "Citizen of Trinidad and Tobago (Wikidata)",
  },
  Q757: {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    text: "Citizen of Saint Vincent and the Grenadines (Wikidata)",
  },
  Q760: {
    name: "Saint Lucia",
    code: "LC",
    text: "Citizen of Saint Lucia (Wikidata)",
  },
  Q763: {
    name: "Saint Kitts and Nevis",
    code: "KN",
    text: "Citizen of Saint Kitts and Nevis (Wikidata)",
  },
  Q766: { name: "Jamaica", code: "JM", text: "Citizen of Jamaica (Wikidata)" },
  Q769: { name: "Grenada", code: "GD", text: "Citizen of Grenada (Wikidata)" },
  Q774: {
    name: "Guatemala",
    code: "GT",
    text: "Citizen of Guatemala (Wikidata)",
  },
  Q778: {
    name: "The Bahamas",
    code: "BS",
    text: "Citizen of The Bahamas (Wikidata)",
  },
  Q781: {
    name: "Antigua and Barbuda",
    code: "AG",
    text: "Citizen of Antigua and Barbuda (Wikidata)",
  },
  Q783: {
    name: "Honduras",
    code: "HN",
    text: "Citizen of Honduras (Wikidata)",
  },
  Q784: {
    name: "Dominica",
    code: "DM",
    text: "Citizen of Dominica (Wikidata)",
  },
  Q786: {
    name: "Dominican Republic",
    code: "DO",
    text: "Citizen of Dominican Republic (Wikidata)",
  },
  Q790: { name: "Haiti", code: "HT", text: "Citizen of Haiti (Wikidata)" },
  Q792: {
    name: "El Salvador",
    code: "SV",
    text: "Citizen of El Salvador (Wikidata)",
  },
  Q794: { name: "Iran", code: "IR", text: "Citizen of Iran (Wikidata)" },
  Q796: { name: "Iraq", code: "IQ", text: "Citizen of Iraq (Wikidata)" },
  Q800: {
    name: "Costa Rica",
    code: "CR",
    text: "Citizen of Costa Rica (Wikidata)",
  },
  Q801: { name: "Israel", code: "IL", text: "Citizen of Israel (Wikidata)" },
  Q805: { name: "Yemen", code: "YE", text: "Citizen of Yemen (Wikidata)" },
  Q810: { name: "Jordan", code: "JO", text: "Citizen of Jordan (Wikidata)" },
  Q811: {
    name: "Nicaragua",
    code: "NI",
    text: "Citizen of Nicaragua (Wikidata)",
  },
  Q813: {
    name: "Kyrgyzstan",
    code: "KG",
    text: "Citizen of Kyrgyzstan (Wikidata)",
  },
  Q819: { name: "Laos", code: "LA", text: "Citizen of Laos (Wikidata)" },
  Q822: { name: "Lebanon", code: "LB", text: "Citizen of Lebanon (Wikidata)" },
  Q826: {
    name: "Maldives",
    code: "MV",
    text: "Citizen of Maldives (Wikidata)",
  },
  Q833: {
    name: "Malaysia",
    code: "MY",
    text: "Citizen of Malaysia (Wikidata)",
  },
  Q836: { name: "Myanmar", code: "MM", text: "Citizen of Myanmar (Wikidata)" },
  Q837: { name: "Nepal", code: "NP", text: "Citizen of Nepal (Wikidata)" },
  Q842: { name: "Oman", code: "OM", text: "Citizen of Oman (Wikidata)" },
  Q843: {
    name: "Pakistan",
    code: "PK",
    text: "Citizen of Pakistan (Wikidata)",
  },
  Q846: { name: "Qatar", code: "QA", text: "Citizen of Qatar (Wikidata)" },
  Q851: {
    name: "Saudi Arabia",
    code: "SA",
    text: "Citizen of Saudi Arabia (Wikidata)",
  },
  Q854: {
    name: "Sri Lanka",
    code: "LK",
    text: "Citizen of Sri Lanka (Wikidata)",
  },
  Q858: { name: "Syria", code: "SY", text: "Citizen of Syria (Wikidata)" },
  Q863: {
    name: "Tajikistan",
    code: "TJ",
    text: "Citizen of Tajikistan (Wikidata)",
  },
  Q865: { name: "Taiwan", code: "TW", text: "Citizen of Taiwan (Wikidata)" },
  Q869: {
    name: "Thailand",
    code: "TH",
    text: "Citizen of Thailand (Wikidata)",
  },
  Q874: {
    name: "Turkmenistan",
    code: "TM",
    text: "Citizen of Turkmenistan (Wikidata)",
  },
  Q878: {
    name: "United Arab Emirates",
    code: "AE",
    text: "Citizen of United Arab Emirates (Wikidata)",
  },
  Q881: { name: "Vietnam", code: "VN", text: "Citizen of Vietnam (Wikidata)" },
  Q884: {
    name: "South Korea",
    code: "KR",
    text: "Citizen of South Korea (Wikidata)",
  },
  Q889: {
    name: "Afghanistan",
    code: "AF",
    text: "Citizen of Afghanistan (Wikidata)",
  },
  Q902: {
    name: "Bangladesh",
    code: "BD",
    text: "Citizen of Bangladesh (Wikidata)",
  },
  Q912: { name: "Mali", code: "ML", text: "Citizen of Mali (Wikidata)" },
  Q916: { name: "Angola", code: "AO", text: "Citizen of Angola (Wikidata)" },
  Q917: { name: "Bhutan", code: "BT", text: "Citizen of Bhutan (Wikidata)" },
  Q921: { name: "Brunei", code: "BN", text: "Citizen of Brunei (Wikidata)" },
  Q924: {
    name: "Tanzania",
    code: "TZ",
    text: "Citizen of Tanzania (Wikidata)",
  },
  Q928: {
    name: "Philippines",
    code: "PH",
    text: "Citizen of Philippines (Wikidata)",
  },
  Q929: {
    name: "Central African Republic",
    code: "CF",
    text: "Citizen of Central African Republic (Wikidata)",
  },
  Q945: { name: "Togo", code: "TG", text: "Citizen of Togo (Wikidata)" },
  Q948: { name: "Tunisia", code: "TN", text: "Citizen of Tunisia (Wikidata)" },
  Q953: { name: "Zambia", code: "ZM", text: "Citizen of Zambia (Wikidata)" },
  Q954: {
    name: "Zimbabwe",
    code: "ZW",
    text: "Citizen of Zimbabwe (Wikidata)",
  },
  Q958: {
    name: "South Sudan",
    code: "SS",
    text: "Citizen of South Sudan (Wikidata)",
  },
  Q962: { name: "Benin", code: "BJ", text: "Citizen of Benin (Wikidata)" },
  Q963: {
    name: "Botswana",
    code: "BW",
    text: "Citizen of Botswana (Wikidata)",
  },
  Q965: {
    name: "Burkina Faso",
    code: "BF",
    text: "Citizen of Burkina Faso (Wikidata)",
  },
  Q967: { name: "Burundi", code: "BI", text: "Citizen of Burundi (Wikidata)" },
  Q970: { name: "Comoros", code: "KM", text: "Citizen of Comoros (Wikidata)" },
  Q971: {
    name: "Republic of the Congo",
    code: "CG",
    text: "Citizen of Republic of the Congo (Wikidata)",
  },
  Q974: {
    name: "Democratic Republic of the Congo",
    code: "CD",
    text: "Citizen of Democratic Republic of the Congo (Wikidata)",
  },
  Q977: {
    name: "Djibouti",
    code: "DJ",
    text: "Citizen of Djibouti (Wikidata)",
  },
  Q986: { name: "Eritrea", code: "ER", text: "Citizen of Eritrea (Wikidata)" },
  Q1005: {
    name: "The Gambia",
    code: "GM",
    text: "Citizen of The Gambia (Wikidata)",
  },
  Q1006: { name: "Guinea", code: "GN", text: "Citizen of Guinea (Wikidata)" },
  Q1007: {
    name: "Guinea-Bissau",
    code: "GW",
    text: "Citizen of Guinea-Bissau (Wikidata)",
  },
  Q1008: {
    name: "Ivory Coast",
    code: "CI",
    text: "Citizen of Ivory Coast (Wikidata)",
  },
  Q1009: {
    name: "Cameroon",
    code: "CM",
    text: "Citizen of Cameroon (Wikidata)",
  },
  Q1011: {
    name: "Cape Verde",
    code: "CV",
    text: "Citizen of Cape Verde (Wikidata)",
  },
  Q1013: { name: "Lesotho", code: "LS", text: "Citizen of Lesotho (Wikidata)" },
  Q1014: { name: "Liberia", code: "LR", text: "Citizen of Liberia (Wikidata)" },
  Q1016: { name: "Libya", code: "LY", text: "Citizen of Libya (Wikidata)" },
  Q1019: {
    name: "Madagascar",
    code: "MG",
    text: "Citizen of Madagascar (Wikidata)",
  },
  Q1020: { name: "Malawi", code: "MW", text: "Citizen of Malawi (Wikidata)" },
  Q1025: {
    name: "Mauritania",
    code: "MR",
    text: "Citizen of Mauritania (Wikidata)",
  },
  Q1027: {
    name: "Mauritius",
    code: "MU",
    text: "Citizen of Mauritius (Wikidata)",
  },
  Q1028: { name: "Morocco", code: "MA", text: "Citizen of Morocco (Wikidata)" },
  Q1029: {
    name: "Mozambique",
    code: "MZ",
    text: "Citizen of Mozambique (Wikidata)",
  },
  Q1030: { name: "Namibia", code: "NA", text: "Citizen of Namibia (Wikidata)" },
  Q1032: { name: "Niger", code: "NE", text: "Citizen of Niger (Wikidata)" },
  Q1033: { name: "Nigeria", code: "NG", text: "Citizen of Nigeria (Wikidata)" },
  Q1036: { name: "Uganda", code: "UG", text: "Citizen of Uganda (Wikidata)" },
  Q1037: { name: "Rwanda", code: "RW", text: "Citizen of Rwanda (Wikidata)" },
  Q1039: {
    name: "São Tomé and Príncipe",
    code: "ST",
    text: "Citizen of São Tomé and Príncipe (Wikidata)",
  },
  Q1041: { name: "Senegal", code: "SN", text: "Citizen of Senegal (Wikidata)" },
  Q1042: {
    name: "Seychelles",
    code: "SC",
    text: "Citizen of Seychelles (Wikidata)",
  },
  Q1044: {
    name: "Sierra Leone",
    code: "SL",
    text: "Citizen of Sierra Leone (Wikidata)",
  },
  Q1045: { name: "Somalia", code: "SO", text: "Citizen of Somalia (Wikidata)" },
  Q1049: { name: "Sudan", code: "SD", text: "Citizen of Sudan (Wikidata)" },
  Q16641: {
    name: "American Samoa",
    code: "AS",
    text: "Citizen of American Samoa (Wikidata)",
  },
  Q16644: {
    name: "Northern Mariana Islands",
    code: "MP",
    text: "Citizen of Northern Mariana Islands (Wikidata)",
  },
  Q21203: { name: "Aruba", code: "AW", text: "Citizen of Aruba (Wikidata)" },
  Q26273: {
    name: "Sint Maarten",
    code: "SX",
    text: "Citizen of Sint Maarten (Wikidata)",
  },
  Q26988: {
    name: "Cook Islands",
    code: "CK",
    text: "Citizen of Cook Islands (Wikidata)",
  },
  Q29999: {
    name: "Kingdom of the Netherlands",
    code: "NL",
    text: "Citizen of Kingdom of the Netherlands (Wikidata)",
  },
  Q34020: { name: "Niue", code: "NU", text: "Citizen of Niue (Wikidata)" },
};

//https://query.wikidata.org/#%23Countries%20with%20country%20code%0ASELECT%20%3Fitem%20%3Fname%20%3Fcode%0AWHERE%20%0A%7B%0A%20%20%3Fitem%20wdt%3AP31%20wd%3AQ6256.%0A%20%20%3Fitem%20wdt%3AP297%20%3Fcode.%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%7D
