export type PropColor = {
  item: string;
  itemLabel: string;
  colorLabel: string;
  hex: string;
};

export const EYE_AND_HAIR_COLORS: PropColor[] = [
  {
    item: "http://www.wikidata.org/entity/Q202466",
    itemLabel: "blond hair",
    colorLabel: "yellow",
    hex: "FFFF00",
  },
  {
    item: "http://www.wikidata.org/entity/Q61196466",
    itemLabel: "yellow hair",
    colorLabel: "yellow",
    hex: "FFFF00",
  },
  {
    item: "http://www.wikidata.org/entity/Q4930092",
    itemLabel: "blue hair",
    colorLabel: "blue",
    hex: "0000FF",
  },
  {
    item: "http://www.wikidata.org/entity/Q26449910",
    itemLabel: "green hair",
    colorLabel: "green",
    hex: "00FF00",
  },
  {
    item: "http://www.wikidata.org/entity/Q152357",
    itemLabel: "red hair",
    colorLabel: "red",
    hex: "FF0000",
  },
  {
    item: "http://www.wikidata.org/entity/Q202466",
    itemLabel: "blond hair",
    colorLabel: "white",
    hex: "FFFFFF",
  },
  {
    item: "http://www.wikidata.org/entity/Q6933946",
    itemLabel: "white hair",
    colorLabel: "white",
    hex: "FFFFFF",
  },
  {
    item: "http://www.wikidata.org/entity/Q1922956",
    itemLabel: "black hair",
    colorLabel: "black",
    hex: "000000",
  },
  {
    item: "http://www.wikidata.org/entity/Q19916539",
    itemLabel: "orange hair",
    colorLabel: "orange",
    hex: "FF7F00",
  },
  {
    item: "http://www.wikidata.org/entity/Q202466",
    itemLabel: "blond hair",
    colorLabel: "grey",
    hex: "808080",
  },
  {
    item: "http://www.wikidata.org/entity/Q10509939",
    itemLabel: "grey hair",
    colorLabel: "grey",
    hex: "808080",
  },
  {
    item: "http://www.wikidata.org/entity/Q202466",
    itemLabel: "blond hair",
    colorLabel: "grey",
    hex: "858585",
  },
  {
    item: "http://www.wikidata.org/entity/Q10509939",
    itemLabel: "grey hair",
    colorLabel: "grey",
    hex: "858585",
  },
  {
    item: "http://www.wikidata.org/entity/Q2367101",
    itemLabel: "brown hair",
    colorLabel: "brown",
    hex: "964B00",
  },
  {
    item: "http://www.wikidata.org/entity/Q81744936",
    itemLabel: "cyan hair",
    colorLabel: "cyan",
    hex: "00FFFF",
  },
  {
    item: "http://www.wikidata.org/entity/Q58628766",
    itemLabel: "silver hair",
    colorLabel: "silver",
    hex: "C0C0C0",
  },
  {
    item: "http://www.wikidata.org/entity/Q27790873",
    itemLabel: "purple hair",
    colorLabel: "violet",
    hex: "7F00FF",
  },
  {
    item: "http://www.wikidata.org/entity/Q28962042",
    itemLabel: "pink hair",
    colorLabel: "pink",
    hex: "FFC0DB",
  },
  {
    item: "http://www.wikidata.org/entity/Q78369542",
    itemLabel: "teal",
    colorLabel: "teal",
    hex: "008080",
  },
  {
    item: "http://www.wikidata.org/entity/Q4930092",
    itemLabel: "blue hair",
    colorLabel: "light blue",
    hex: "ADD8E6",
  },
  {
    item: "http://www.wikidata.org/entity/Q61507574",
    itemLabel: "light blue hair",
    colorLabel: "light blue",
    hex: "ADD8E6",
  },
  {
    item: "http://www.wikidata.org/entity/Q5094009",
    itemLabel: "chestnut hair",
    colorLabel: "chestnut",
    hex: "954535",
  },
  {
    item: "http://www.wikidata.org/entity/Q59297065",
    itemLabel: "lavender hair",
    colorLabel: "lavender",
    hex: "B57EDC",
  },
  {
    item: "http://www.wikidata.org/entity/Q87069502",
    itemLabel: "wine hair",
    colorLabel: "wine",
    hex: "722F37",
  },
  {
    item: "http://www.wikidata.org/entity/Q87069502",
    itemLabel: "wine hair",
    colorLabel: "wine",
    hex: "AC1E44",
  },
  {
    item: "http://www.wikidata.org/entity/Q87069502",
    itemLabel: "wine hair",
    colorLabel: "wine",
    hex: "C0007F",
  },
  {
    item: "http://www.wikidata.org/entity/Q27790873",
    itemLabel: "purple hair",
    colorLabel: "purple",
    hex: "800080",
  },
  {
    item: "http://www.wikidata.org/entity/Q78375121",
    itemLabel: "dark blue hair",
    colorLabel: "dark blue",
    hex: "00008B",
  },
  {
    item: "http://www.wikidata.org/entity/Q79902046",
    itemLabel: "light green hair",
    colorLabel: "light green",
    hex: "99FF99",
  },
  {
    item: "http://www.wikidata.org/entity/Q100136341",
    itemLabel: "turquoise hair",
    colorLabel: "turquoise",
    hex: "40E0D0",
  },
  {
    item: "http://www.wikidata.org/entity/Q100136341",
    itemLabel: "turquoise hair",
    colorLabel: "turquoise",
    hex: "30D5C8",
  },
  {
    item: "http://www.wikidata.org/entity/Q100136341",
    itemLabel: "turquoise hair",
    colorLabel: "turquoise",
    hex: "45B5AA",
  },
  {
    item: "http://www.wikidata.org/entity/Q28961883",
    itemLabel: "dark brown hair",
    colorLabel: "dark brown",
    hex: "654321",
  },
  {
    item: "http://www.wikidata.org/entity/Q79483987",
    itemLabel: "dark green hair",
    colorLabel: "dark green",
    hex: "006400",
  },
  {
    item: "http://www.wikidata.org/entity/Q79483632",
    itemLabel: "light brown hair",
    colorLabel: "light brown",
    hex: "B5651D",
  },
  {
    item: "http://www.wikidata.org/entity/Q27777837",
    itemLabel: "yellow",
    colorLabel: "yellow",
    hex: "FFFF00",
  },
  {
    item: "http://www.wikidata.org/entity/Q17122834",
    itemLabel: "blue",
    colorLabel: "blue",
    hex: "0000FF",
  },
  {
    item: "http://www.wikidata.org/entity/Q17122854",
    itemLabel: "green",
    colorLabel: "green",
    hex: "00FF00",
  },
  {
    item: "http://www.wikidata.org/entity/Q17126729",
    itemLabel: "red",
    colorLabel: "red",
    hex: "FF0000",
  },
  {
    item: "http://www.wikidata.org/entity/Q62391724",
    itemLabel: "white",
    colorLabel: "white",
    hex: "FFFFFF",
  },
  {
    item: "http://www.wikidata.org/entity/Q17244465",
    itemLabel: "black",
    colorLabel: "black",
    hex: "000000",
  },
  {
    item: "http://www.wikidata.org/entity/Q59318527",
    itemLabel: "orange",
    colorLabel: "orange",
    hex: "FF7F00",
  },
  {
    item: "http://www.wikidata.org/entity/Q17245659",
    itemLabel: "gray",
    colorLabel: "grey",
    hex: "808080",
  },
  {
    item: "http://www.wikidata.org/entity/Q17245659",
    itemLabel: "gray",
    colorLabel: "grey",
    hex: "858585",
  },
  {
    item: "http://www.wikidata.org/entity/Q17122705",
    itemLabel: "brown",
    colorLabel: "brown",
    hex: "964B00",
  },
  {
    item: "http://www.wikidata.org/entity/Q87067369",
    itemLabel: "cyan",
    colorLabel: "cyan",
    hex: "00FFFF",
  },
  {
    item: "http://www.wikidata.org/entity/Q66821598",
    itemLabel: "silver",
    colorLabel: "silver",
    hex: "C0C0C0",
  },
  {
    item: "http://www.wikidata.org/entity/Q87067369",
    itemLabel: "cyan",
    colorLabel: "aqua",
    hex: "00FFFF",
  },
  {
    item: "http://www.wikidata.org/entity/Q87067369",
    itemLabel: "cyan",
    colorLabel: "aquamarine",
    hex: "7FFFD4",
  },
  {
    item: "http://www.wikidata.org/entity/Q17122834",
    itemLabel: "blue",
    colorLabel: "sky blue",
    hex: "77B5FE",
  },
  {
    item: "http://www.wikidata.org/entity/Q27839441",
    itemLabel: "purple",
    colorLabel: "violet",
    hex: "7F00FF",
  },
  {
    item: "http://www.wikidata.org/entity/Q59318252",
    itemLabel: "pink",
    colorLabel: "pink",
    hex: "FFC0DB",
  },
  {
    item: "http://www.wikidata.org/entity/Q3375649",
    itemLabel: "blue-green",
    colorLabel: "blue-green",
    hex: "0D98BA",
  },
  {
    item: "http://www.wikidata.org/entity/Q3375649",
    itemLabel: "blue-green",
    colorLabel: "blue-green",
    hex: "009C8C",
  },
  {
    item: "http://www.wikidata.org/entity/Q3375649",
    itemLabel: "blue-green",
    colorLabel: "blue-green",
    hex: "80FFCE",
  },
  {
    item: "http://www.wikidata.org/entity/Q17291407",
    itemLabel: "amber",
    colorLabel: "amber",
    hex: "FFBF00",
  },
  {
    item: "http://www.wikidata.org/entity/Q87067389",
    itemLabel: "teal",
    colorLabel: "teal",
    hex: "008080",
  },
  {
    item: "http://www.wikidata.org/entity/Q61600018",
    itemLabel: "light blue",
    colorLabel: "light blue",
    hex: "ADD8E6",
  },
  {
    item: "http://www.wikidata.org/entity/Q100134571",
    itemLabel: "chestnut",
    colorLabel: "chestnut",
    hex: "954535",
  },
  {
    item: "http://www.wikidata.org/entity/Q100132309",
    itemLabel: "sapphire",
    colorLabel: "sapphire",
    hex: "082567",
  },
  {
    item: "http://www.wikidata.org/entity/Q100134963",
    itemLabel: "lavender",
    colorLabel: "lavender",
    hex: "B57EDC",
  },
  {
    item: "http://www.wikidata.org/entity/Q100292098",
    itemLabel: "coffee",
    colorLabel: "coffee",
    hex: "6F4E37",
  },
  {
    item: "http://www.wikidata.org/entity/Q27839441",
    itemLabel: "purple",
    colorLabel: "purple",
    hex: "800080",
  },
  {
    item: "http://www.wikidata.org/entity/Q60172366",
    itemLabel: "dark blue",
    colorLabel: "dark blue",
    hex: "00008B",
  },
  {
    item: "http://www.wikidata.org/entity/Q78374938",
    itemLabel: "light green",
    colorLabel: "light green",
    hex: "99FF99",
  },
  {
    item: "http://www.wikidata.org/entity/Q42845936",
    itemLabel: "blue-gray",
    colorLabel: "blue-gray",
    hex: "6699CC",
  },
  {
    item: "http://www.wikidata.org/entity/Q87067369",
    itemLabel: "cyan",
    colorLabel: "turquoise",
    hex: "40E0D0",
  },
  {
    item: "http://www.wikidata.org/entity/Q100136258",
    itemLabel: "turquoise",
    colorLabel: "turquoise",
    hex: "40E0D0",
  },
  {
    item: "http://www.wikidata.org/entity/Q87067369",
    itemLabel: "cyan",
    colorLabel: "turquoise",
    hex: "30D5C8",
  },
  {
    item: "http://www.wikidata.org/entity/Q100136258",
    itemLabel: "turquoise",
    colorLabel: "turquoise",
    hex: "30D5C8",
  },
  {
    item: "http://www.wikidata.org/entity/Q87067369",
    itemLabel: "cyan",
    colorLabel: "turquoise",
    hex: "45B5AA",
  },
  {
    item: "http://www.wikidata.org/entity/Q100136258",
    itemLabel: "turquoise",
    colorLabel: "turquoise",
    hex: "45B5AA",
  },
  {
    item: "http://www.wikidata.org/entity/Q17244894",
    itemLabel: "dark brown",
    colorLabel: "dark brown",
    hex: "654321",
  },
  {
    item: "http://www.wikidata.org/entity/Q79401007",
    itemLabel: "dark green",
    colorLabel: "dark green",
    hex: "006400",
  },
  {
    item: "http://www.wikidata.org/entity/Q17122740",
    itemLabel: "hazel",
    colorLabel: "hazel",
    hex: "B5AE6E",
  },
  {
    item: "http://www.wikidata.org/entity/Q79399164",
    itemLabel: "light brown",
    colorLabel: "light brown",
    hex: "B5651D",
  },
];

//https://query.wikidata.org/#%23Goats%0ASELECT%20%3Fitem%20%3FitemLabel%20%3FcolorLabel%20%3Fhex%0AWHERE%20%0A%7B%0A%20%20%3Fitem%20wdt%3AP31%20wd%3AQ23786.%0A%20%20%3Fitem%20wdt%3AP462%20%3Fcolor.%0A%20%20%3Fcolor%20wdt%3AP465%20%3Fhex.%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%7D

//https://query.wikidata.org/#%23Eye%20colors%20and%20hair%20colors%0ASELECT%20%3Fitem%20%3FitemLabel%20%3FcolorLabel%20%3Fhex%0AWHERE%20%0A%7B%0A%20%20%7B%3Fitem%20wdt%3AP31%20wd%3AQ23786%7D%20UNION%20%7B%3Fitem%20wdt%3AP31%20wd%3AQ1048314%7D.%0A%20%20%0A%20%20%3Fitem%20wdt%3AP462%20%3Fcolor.%0A%20%20%3Fcolor%20wdt%3AP465%20%3Fhex.%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%7D
