import { Lang, LangCode } from "types/Lang";

const DISAMBIGUATION_PAGE_DESC = {
  ar: "صفحة توضيح لويكيميديا",
  da: "Wikipedia-flertydigside",
  de: "Wikimedia-Begriffsklärungsseite",
  en: "Wikimedia disambiguation page",
  es: "página de desambiguación de Wikimedia",
  fr: "page d'homonymie de Wikimedia",
  id: "halaman disambiguasi Wikimedia",
  it: "pagina di disambiguazione di un progetto Wikimedia",
  ja: "ウィキメディアの曖昧さ回避ページ",
  hi: "बहुविकल्पी पृष्ठ",
  hu: "egyértelműsítő lap",
  nl: "Wikimedia-doorverwijspagina",
  pl: "strona ujednoznaczniająca",
  pt: "página de desambiguação de um projeto da Wikimedia",
  ru: "страница значений в проекте Викимедиа",
  zh: "維基媒體消歧義頁",
  ne: "------",
};

export const ALL_LANGS = {
  abs: "Ambonese Malay",
  ab: "Abkhazian",
  ace: "Achinese",
  ady: "Adyghe",
  "ady-cyrl": "Adyghe (Cyrillic script)",
  aeb: "Tunisian Arabic",
  "aeb-arab": "Tunisian Arabic (Arabic script)",
  "aeb-latn": "Tunisian Arabic (Latin script)",
  af: "Afrikaans",
  ak: "Akan",
  aln: "Gheg Albanian",
  am: "Amharic",
  an: "Aragonese",
  // ang: "Old English",
  anp: "Angika",
  ar: "Arabic",
  arc: "Aramaic",
  arn: "Mapuche",
  arq: "Algerian Arabic",
  ary: "Moroccan Arabic",
  arz: "Egyptian Arabic",
  as: "Assamese",
  ase: "American Sign Language",
  ast: "Asturian",
  atj: "Atikamekw",
  av: "Avaric",
  avk: "Kotava",
  awa: "Awadhi",
  ay: "Aymara",
  az: "Azerbaijani",
  azb: "South Azerbaijani",
  ba: "Bashkir",
  ban: "Balinese",
  bar: "Bavarian",
  bbc: "Batak Toba",
  "bbc-latn": "Batak Toba (Latin script)",
  bcc: "Southern Balochi",
  bcl: "Central Bikol",
  be: "Belarusian",
  "be-tarask": "Belarusian (Taraškievica orthography)",
  bg: "Bulgarian",
  bgn: "Western Balochi",
  bh: "Bhojpuri",
  bho: "Bhojpuri",
  bi: "Bislama",
  bjn: "Banjar",
  bm: "Bambara",
  bn: "Bangla",
  bo: "Tibetan",
  bpy: "Bishnupriya",
  bqi: "Bakhtiari",
  br: "Breton",
  brh: "Brahui",
  bs: "Bosnian",
  btm: "Batak Mandailing",
  bto: "Iriga Bicolano",
  bug: "Buginese",
  bxr: "Russia Buriat",
  ca: "Catalan",
  "cbk-zam": "Chavacano",
  cdo: "Min Dong Chinese",
  ce: "Chechen",
  ceb: "Cebuano",
  ch: "Chamorro",
  chr: "Cherokee",
  chy: "Cheyenne",
  ckb: "Central Kurdish",
  co: "Corsican",
  cps: "Capiznon",
  cr: "Cree",
  crh: "Crimean Turkish",
  "crh-cyrl": "Crimean Tatar (Cyrillic script)",
  "crh-latn": "Crimean Tatar (Latin script)",
  cs: "Czech",
  csb: "Kashubian",
  cu: "Church Slavic",
  cv: "Chuvash",
  cy: "Welsh",
  da: "Danish",
  de: "German",
  "de-at": "Austrian German",
  "de-ch": "Swiss High German",
  // "de-formal": "German (formal address)",
  din: "Dinka",
  diq: "Zazaki",
  dsb: "Lower Sorbian",
  dtp: "Central Dusun",
  dty: "Doteli",
  dv: "Divehi",
  dz: "Dzongkha",
  ee: "Ewe",
  egl: "Emilian",
  el: "Greek",
  eml: "Emiliano-Romagnolo",
  en: "English",
  "en-ca": "Canadian English",
  "en-gb": "British English",
  eo: "Esperanto",
  es: "Spanish",
  // "es-formal": "español (formal)‎",
  et: "Estonian",
  eu: "Basque",
  ext: "Extremaduran",
  fa: "Persian",
  ff: "Fulah",
  fi: "Finnish",
  fit: "Tornedalen Finnish",
  fj: "Fijian",
  fo: "Faroese",
  fr: "French",
  frc: "Cajun French",
  frp: "Arpitan",
  frr: "Northern Frisian",
  fur: "Friulian",
  fy: "Western Frisian",
  ga: "Irish",
  gag: "Gagauz",
  gan: "Gan Chinese",
  "gan-hans": "Gan (Simplified)",
  "gan-hant": "Gan (Traditional)",
  gcr: "Guianan Creole",
  gd: "Scottish Gaelic",
  gl: "Galician",
  glk: "Gilaki",
  gn: "Guarani",
  gom: "Goan Konkani",
  "gom-deva": "Goan Konkani (Devanagari script)",
  "gom-latn": "Goan Konkani (Latin script)",
  gor: "Gorontalo",
  got: "Gothic",
  grc: "Ancient Greek",
  gsw: "Swiss German",
  gu: "Gujarati",
  gv: "Manx",
  ha: "Hausa",
  hak: "Hakka Chinese",
  haw: "Hawaiian",
  he: "Hebrew",
  hi: "Hindi",
  hif: "Fiji Hindi",
  "hif-latn": "Fiji Hindi (Latin script)",
  hil: "Hiligaynon",
  hr: "Croatian",
  hrx: "Hunsrik",
  hsb: "Upper Sorbian",
  ht: "Haitian Creole",
  hu: "Hungarian",
  // "hu-formal": "magyar (formal)‎",
  hy: "Armenian",
  hyw: "Western Armenian",
  ia: "Interlingua",
  id: "Indonesian",
  ie: "Interlingue",
  ig: "Igbo",
  ii: "Sichuan Yi",
  ik: "Inupiaq",
  "ike-cans": "Eastern Canadian (Aboriginal syllabics)",
  "ike-latn": "Eastern Canadian (Latin script)",
  ilo: "Iloko",
  inh: "Ingush",
  io: "Ido",
  is: "Icelandic",
  it: "Italian",
  iu: "Inuktitut",
  ja: "Japanese",
  jam: "Jamaican Creole English",
  jbo: "Lojban",
  jut: "Jutish",
  jv: "Javanese",
  ka: "Georgian",
  kaa: "Kara-Kalpak",
  kab: "Kabyle",
  kbd: "Kabardian",
  "kbd-cyrl": "Kabardian (Cyrillic script)",
  kbp: "Kabiye",
  kg: "Kongo",
  khw: "Khowar",
  ki: "Kikuyu",
  kiu: "Kirmanjki",
  kjp: "Eastern Pwo",
  kk: "Kazakh",
  "kk-arab": "Kazakh (Arabic script)",
  "kk-cn": "Kazakh (China)",
  "kk-cyrl": "Kazakh (Cyrillic script)",
  "kk-kz": "Kazakh (Kazakhstan)",
  "kk-latn": "Kazakh (Latin script)",
  "kk-tr": "Kazakh (Turkey)",
  kl: "Kalaallisut",
  km: "Khmer",
  kn: "Kannada",
  ko: "Korean",
  "ko-kp": "Korean (North Korea)",
  koi: "Komi-Permyak",
  krc: "Karachay-Balkar",
  kri: "Krio",
  krj: "Kinaray-a",
  krl: "Karelian",
  ks: "Kashmiri",
  "ks-arab": "Kashmiri (Arabic script)",
  "ks-deva": "Kashmiri (Devanagari script)",
  ksh: "Colognian",
  ku: "Kurdish",
  "ku-arab": "Kurdish (Arabic script)",
  "ku-latn": "Kurdish (Latin script)",
  kum: "Kumyk",
  kv: "Komi",
  kw: "Cornish",
  ky: "Kyrgyz",
  la: "Latin",
  lad: "Ladino",
  lb: "Luxembourgish",
  lbe: "Lak",
  lez: "Lezghian",
  lfn: "Lingua Franca Nova",
  lg: "Ganda",
  li: "Limburgish",
  lij: "Ligurian",
  liv: "Livonian",
  lki: "Laki",
  lmo: "Lombard",
  ln: "Lingala",
  lo: "Lao",
  loz: "Lozi",
  lrc: "Northern Luri",
  lt: "Lithuanian",
  ltg: "Latgalian",
  lus: "Mizo",
  luz: "Southern Luri",
  lv: "Latvian",
  lzh: "Literary Chinese",
  lzz: "Laz",
  mai: "Maithili",
  "map-bms": "Basa Banyumasan",
  mdf: "Moksha",
  mg: "Malagasy",
  mhr: "Eastern Mari",
  mi: "Maori",
  min: "Minangkabau",
  mk: "Macedonian",
  ml: "Malayalam",
  mn: "Mongolian",
  mni: "Manipuri",
  mnw: "Mon",
  mo: "Moldovan",
  mr: "Marathi",
  mrj: "Western Mari",
  ms: "Malay",
  mt: "Maltese",
  mwl: "Mirandese",
  my: "Burmese",
  myv: "Erzya",
  mzn: "Mazanderani",
  na: "Nauru",
  nah: "Nāhuatl",
  nan: "Min Nan Chinese",
  nap: "Neapolitan",
  nb: "Norwegian Bokmål",
  nds: "Low German",
  "nds-nl": "Low Saxon",
  ne: "Nepali",
  new: "Newari",
  niu: "Niuean",
  nl: "Dutch",
  // "nl-informal": "Nederlands (informeel)‎",
  nn: "Norwegian Nynorsk",
  nov: "Novial",
  nqo: "N’Ko",
  nrm: "Norman",
  nso: "Northern Sotho",
  nv: "Navajo",
  ny: "Nyanja",
  nys: "Nyungar",
  oc: "Occitan",
  olo: "Livvi-Karelian",
  om: "Oromo",
  or: "Odia",
  os: "Ossetic",
  pa: "Punjabi",
  pag: "Pangasinan",
  pam: "Pampanga",
  pap: "Papiamento",
  pcd: "Picard",
  pdc: "Pennsylvania German",
  pdt: "Plautdietsch",
  pfl: "Palatine German",
  pi: "Pali",
  pih: "Norfuk / Pitkern",
  pl: "Polish",
  pms: "Piedmontese",
  pnb: "Western Punjabi",
  pnt: "Pontic",
  prg: "Prussian",
  ps: "Pashto",
  pt: "Portuguese",
  "pt-br": "Brazilian Portuguese",
  qu: "Quechua",
  qug: "Chimborazo Highland Quichua",
  rgn: "Romagnol",
  rif: "Riffian",
  rm: "Romansh",
  rmy: "Vlax Romani",
  ro: "Romanian",
  "roa-tara": "Tarantino",
  ru: "Russian",
  rue: "Rusyn",
  rup: "Aromanian",
  ruq: "Megleno-Romanian",
  "ruq-cyrl": "Megleno-Romanian (Cyrillic script)",
  "ruq-latn": "Megleno-Romanian (Latin script)",
  rw: "Kinyarwanda",
  sa: "Sanskrit",
  sah: "Sakha",
  sat: "Santali",
  sc: "Sardinian",
  scn: "Sicilian",
  sco: "Scots",
  sd: "Sindhi",
  sdc: "Sassarese Sardinian",
  sdh: "Southern Kurdish",
  se: "Northern Sami",
  sei: "Seri",
  ses: "Koyraboro Senni",
  sg: "Sango",
  sgs: "Samogitian",
  sh: "Serbo-Croatian",
  shi: "Tachelhit",
  shn: "Shan",
  "shy-latn": "Shawiya (Latin script)",
  si: "Sinhala",
  sk: "Slovak",
  skr: "Saraiki",
  "skr-arab": "Saraiki (Arabic script)",
  sl: "Slovenian",
  sli: "Lower Silesian",
  sm: "Samoan",
  sma: "Southern Sami",
  smn: "Inari Sami",
  sn: "Shona",
  so: "Somali",
  sq: "Albanian",
  sr: "Serbian",
  "sr-ec": "Serbian (Cyrillic script)",
  "sr-el": "Serbian (Latin script)",
  srn: "Sranan Tongo",
  ss: "Swati",
  st: "Southern Sotho",
  stq: "Saterland Frisian",
  sty: "cебертатар",
  su: "Sundanese",
  sv: "Swedish",
  sw: "Swahili",
  szl: "Silesian",
  szy: "Sakizaya",
  ta: "Tamil",
  tay: "Tayal",
  tcy: "Tulu",
  te: "Telugu",
  tet: "Tetum",
  tg: "Tajik",
  "tg-cyrl": "Tajik (Cyrillic script)",
  "tg-latn": "Tajik (Latin script)",
  th: "Thai",
  ti: "Tigrinya",
  tk: "Turkmen",
  tl: "Tagalog",
  tly: "Talysh",
  tn: "Tswana",
  to: "Tongan",
  tpi: "Tok Pisin",
  tr: "Turkish",
  tru: "Turoyo",
  ts: "Tsonga",
  tt: "Tatar",
  "tt-cyrl": "Tatar (Cyrillic script)",
  "tt-latn": "Tatar (Latin script)",
  tw: "Twi",
  ty: "Tahitian",
  tyv: "Tuvinian",
  tzm: "Central Atlas Tamazight",
  udm: "Udmurt",
  ug: "Uyghur",
  "ug-arab": "Uyghur (Arabic script)",
  "ug-latn": "Uyghur (Latin script)",
  uk: "Ukrainian",
  ur: "Urdu",
  uz: "Uzbek",
  ve: "Venda",
  vec: "Venetian",
  vep: "Veps",
  vi: "Vietnamese",
  vls: "West Flemish",
  vmf: "Main-Franconian",
  vo: "Volapük",
  vot: "Votic",
  vro: "Võro",
  wa: "Walloon",
  war: "Waray",
  wo: "Wolof",
  wuu: "Wu Chinese",
  xal: "Kalmyk",
  xh: "Xhosa",
  xmf: "Mingrelian",
  xsy: "Saisiyat",
  yi: "Yiddish",
  yo: "Yoruba",
  yue: "Cantonese",
  za: "Zhuang",
  zea: "Zeelandic",
  zgh: "Standard Moroccan Tamazight",
  zh: "Chinese",
  "zh-cn": "Chinese (China)",
  "zh-hans": "Simplified Chinese",
  "zh-hant": "Traditional Chinese",
  "zh-hk": "Chinese (Hong Kong)",
  "zh-mo": "Chinese (Macau)",
  "zh-my": "Chinese (Malaysia)",
  "zh-sg": "Chinese (Singapore)",
  "zh-tw": "Chinese (Taiwan)",
  zu: "Zulu",
};

export const LANGS = Object.keys(ALL_LANGS).map((code) => {
  return {
    code,
    name: ALL_LANGS[code],
    disambPageDesc: DISAMBIGUATION_PAGE_DESC[code],
  } as Lang;
});

export const DEFAULT_LANG_CODE = "en";

export const DEFAULT_LANG = LANGS.find(
  (lang) => lang.code === DEFAULT_LANG_CODE,
)!;

//TODO This "could" match all supported langs, so changing lang doesn't need a reload
//Fetch always langs that have disambig page translation (main languages)
export const DEFAULT_LANGS_CODES: LangCode[] = Object.keys(
  DISAMBIGUATION_PAGE_DESC,
) as LangCode[];

export const FAMILY_TREE_PROP_TRANSLATIONS = {
  "zh-hans": "家族树",
  "zh-hant": "家族樹",
  "zh-hk": "家族樹",
  "zh-cn": "家族树",
  "zh-sg": "家族树",
  "zh-tw": "家族樹",
  pl: "Drzewo genealogiczne",
  eu: "Zuhaitz genealogiko",
  es: "árbol genealógico",
  or: "ବଂଶାବଳୀ",
  hu: "családfa",
  ms: "Salasilah keluarga",
  it: "albero genealogico",
  et: "Sugupuu",
  de: "Stammbaum",
  id: "Bagan silsilah",
  br: "Gwezenn-gerentiezh",
  el: "Γενεαλογικό δέντρο",
  sh: "Obiteljsko stablo",
  ar: "شجرة العائلة",
  sv: "Släktträd",
  nl: "stamboom",
  pt: "árvore genealógica",
  eo: "genealogia arbo",
  sk: "Rodokmeň",
  ru: "генеалогическое древо",
  tt: "Шәҗәрә",
  en: "family tree",
  tr: "Soy ağacı",
  ro: "Arbore genealogic",
  ca: "arbre genealògic",
  fi: "Sukupuu",
  cy: "Coeden deulu",
  sl: "Družinsko drevo",
  cs: "rodokmen",
  fa: "تبارنامه",
  hr: "Obiteljsko stablo",
  "kk-arab": "گەنەالوگىييالىك اعاش",
  "kk-cn": "گەنەالوگىييالىك اعاش",
  "kk-tr": "Genealogïyalık ağaş",
  "kk-kz": "Генеалогиялык ағаш",
  "kk-cyrl": "Генеалогиялык ағаш",
  "kk-latn": "Genealogïyalık ağaş",
  da: "Efterslægtstavle",
  ko: "가계도",
  kk: "Генеалогиялык ағаш",
  sah: "Төрүччү",
  zh: "谱系图",
  gl: "Árbore xenealóxica",
  bn: "কুলজিনামা",
  uk: "Генеалогічне дерево",
  ta: "குடும்ப மரம்",
  fr: "arbre généalogique",
  sr: "породично стабло",
  "sr-ec": "породично стабло",
  "sr-el": "porodično stablo",
  lv: "Ciltskoks",
  sco: "faimily tree",
  az: "Nəsil şəcərəsi",
  ja: "系図",
  hi: "वंशावली",
  he: "אילן יוחסין",
  la: "Arbor familiaris",
  nb: "stamtre",
  hyw: "Տոհմածառ",
  hy: "տոհմածառ",
  vro: "Sugupuu",
};
