export interface VideoLink {
  qid: string;
  url: string;
  channel?: string;
  label?: string;
  title?: string;
  embedLink?: string;
  language?: string;
}

export const YOUTUBE_LINKS: Record<string, VideoLink> = {
  Q712401: {
    qid: "Q712401",
    url: "https://www.youtube.com/watch?v=xL2PpDXvfXA",
    embedLink: "https://www.youtube.com/embed/xL2PpDXvfXA",
    title: "The Salim family tree and its businesses: Indofood & IndoAgri",
    channel: "Entitree",
    label: "Salim family",
  },
  Q8409: {
    qid: "Q8409",
    url: "https://www.youtube.com/watch?v=NgK4fJ709Xo",
    embedLink: "https://www.youtube.com/embed/NgK4fJ709Xo",
    title: "Alexander the Great Family Tree",
    channel: "UsefulCharts",
    label: "Alexander the great",
  },
  Q6279: {
    qid: "Q6279",
    url: "https://www.youtube.com/watch?v=L-2eYJBZKXY",
    embedLink: "https://www.youtube.com/embed/L-2eYJBZKXY",
    title: "Joe Biden Family Tree | President of the United States",
    channel: "UsefulCharts",
    label: "Joe Biden",
  },
  Q56226: {
    qid: "Q56226",
    url: "https://www.youtube.com/watch?v=SjKB3BQlgks",
    embedLink: "https://www.youtube.com/embed/SjKB3BQlgks",
    title: "Who Would Be Leader of North Korea if Kim Jong-un Died?",
    channel: "UsefulCharts",
    label: "Kim Jong-un",
  },
  Q180589: {
    qid: "Q180589",
    url: "https://www.youtube.com/watch?v=b48PqY2hd38",
    embedLink: "https://www.youtube.com/embed/b48PqY2hd38",
    title: "Boris Johnson Family Tree",
    channel: "UsefulCharts",
    label: "Boris Johnson",
  },
  Q9696: {
    qid: "Q9696",
    url: "https://www.youtube.com/watch?v=F9TZ5UHMPAE",
    embedLink: "https://www.youtube.com/embed/F9TZ5UHMPAE",
    title: "Kennedy Family Tree",
    channel: "UsefulCharts",
    label: "John F. Kennedy",
  },
  Q76988: {
    qid: "Q76988",
    url: "https://www.youtube.com/watch?v=hr1hisvjoAI",
    embedLink: "https://www.youtube.com/embed/hr1hisvjoAI",
    title: "Rothschild Family Tree",
    channel: "UsefulCharts",
    label: "Mayer Amschel Rothschild",
  },
  Q355288: {
    qid: "Q355288",
    url: "https://www.youtube.com/watch?v=sFqxYkraTrY",
    embedLink: "https://www.youtube.com/embed/sFqxYkraTrY",
    title: "Berry Gordy Family Tree | Jimmy Carter's Motown Cousins",
    channel: "UsefulCharts",
    label: "Berry Gordy",
  },
  Q298263: {
    qid: "Q298263",
    url: "https://www.youtube.com/watch?v=zaC_J-FNZKY",
    embedLink: "https://www.youtube.com/embed/zaC_J-FNZKY",
    title: "Scottish Monarchs Family Tree | Kenneth MacAlpin to James VI",
    channel: "UsefulCharts",
    label: "Kenneth mac Alpin",
  },
  Q280856: {
    qid: "Q280856",
    url: "https://www.youtube.com/watch?v=412rjcZ44Rk",
    embedLink: "https://www.youtube.com/embed/412rjcZ44Rk",
    title:
      "British Monarchy Family Tree | Alfred the Great to Queen Elizabeth II",
    channel: "UsefulCharts",
    label: "George VI",
  },
  Q9441: {
    qid: "Q9441",
    url: "https://www.youtube.com/watch?v=-ijZrPIRlhw",
    embedLink: "https://www.youtube.com/embed/-ijZrPIRlhw",
    title: "Buddha's Family Tree + Did Buddha Exist?",
    channel: "UsefulCharts",
    label: "Gautama Buddha",
  },
  Q9685: {
    qid: "Q9685",
    url: "https://www.youtube.com/watch?v=uCC4NxG74i8",
    embedLink: "https://www.youtube.com/embed/uCC4NxG74i8",
    title: "Princess Diana Family Tree | Spencer-Churchill Dynasty",
    channel: "UsefulCharts",
    label: "Princess Diana",
  },
  Q369920: {
    qid: "Q369920",
    url: "https://www.youtube.com/watch?v=oF1FvMCYaEs",
    embedLink: "https://www.youtube.com/embed/oF1FvMCYaEs",
    title: "Sikh Gurus Family Tree",
    channel: "UsefulCharts",
    label: "Guru Arjan",
  },
  //Fictional person
  Q45792: {
    qid: "Q45792",
    url: "https://www.youtube.com/watch?v=GAlhknnXkL0",
    embedLink: "https://www.youtube.com/embed/GAlhknnXkL0",
    title: "King Arthur Family Tree",
    channel: "UsefulCharts",
    label: "King Arthur",
  },
  Q3454159: {
    qid: "Q3454159",
    url: "https://www.youtube.com/watch?v=DH3lEbQkOzk",
    embedLink: "https://www.youtube.com/embed/DH3lEbQkOzk",
    title: "History of Sri Lanka and the Family Tree of Sri Lankan Kings",
    channel: "UsefulCharts",
    label: "Rajasinghe II of Kandy",
  },
  Q7996: {
    qid: "Q7996",
    url: "https://www.youtube.com/watch?v=OE1Ib9r2ooo",
    embedLink: "https://www.youtube.com/embed/OE1Ib9r2ooo",
    title: "Russian Tsars Family Tree | Ivan the Terrible to Nicholas II",
    channel: "UsefulCharts",
    label: "Ivan the Terrible",
  },
  Q302: {
    qid: "Q302",
    url: "https://www.youtube.com/watch?v=E8jpqeg8Gws",
    embedLink: "https://www.youtube.com/embed/E8jpqeg8Gws",
    title: "Genealogy of Jesus",
    channel: "UsefulCharts",
    label: "Jesus",
  },
  Q185790: {
    qid: "Q185790",
    url: "https://www.youtube.com/watch?v=-vg-5zkw6H4",
    embedLink: "https://www.youtube.com/embed/-vg-5zkw6H4",
    title: "Mahabharata Family Tree | India's Greatest Epic",
    channel: "UsefulCharts",
    label: "Arjuna",
  },
  Q191045: {
    qid: "Q191045",
    url: "https://www.youtube.com/watch?v=uyme3z3xwic",
    embedLink: "https://www.youtube.com/embed/uyme3z3xwic",
    title: "Spanish Monarchs Family Tree | Pelayo to Felipe VI",
    channel: "UsefulCharts",
    label: "Felipe VI",
  },
  Q22686: {
    qid: "Q22686",
    url: "https://www.youtube.com/watch?v=5h3N7v1xAUA",
    embedLink: "https://www.youtube.com/embed/5h3N7v1xAUA",
    title: "Donald Trump Family Tree",
    channel: "UsefulCharts",
    label: "Donald Trump",
  },
  TEMPLATE: {
    qid: "",
    url: "https://www.youtube.com/watch?v=",
    embedLink: "https://www.youtube.com/embed/",
    title: "",
    channel: "UsefulCharts",
    label: "",
  },
};
